# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-24 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='song',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
